<template>

  <div id="app" class="small-container">
    <h1>Employees</h1>
    <employee-form @add:employee="addEmployee" />
    <employee-table :employees="employees" />
  </div>
</template>

<script>
import EmployeeForm from './components/EmployeeForm.vue'

import EmployeeTable from './components/EmployeeTable.vue'

export default {
  name: 'App',
  components: { EmployeeTable, EmployeeForm },

  data() {
    return {
      employees: [
        {
          id: 1,
          name: 'Callum Gill',
          email: 'Callum@employer.com'
        },

        {
          id: 2,
          name: 'James Jefferson',
          email: 'Jefferson@employer.com'
        },

        {
          id: 3,
          name: 'Wild Bill',
          email: 'Bill@employer.com'
        },
      ]
    }
  },
  methods: {
    addEmployee(employee){

      //Note - this part would be auto generated by a db in real world app
      const lastId = this.employees.length > 0 ? this.employees[this.employees.length - 1].id : 0;
      const id = lastId + 1;
      const newEmployee = {...employee, id};

      this.employees = [...this.employees, newEmployee]
    }
  }
  
}
</script>

<style>

 button{
   background: #009435;
   border: 1px solid #009435;
 }

 .small-container {
   max-width: 680px;
 }
</style>
